version: '3.8'
services:
  # app:
  app:
    # platform: linux/arm64
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    # command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb -E production
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - /var/tmp
      - .:/app
    depends_on:
      - db
    extends:
      file: ./mysql/password.yml
      service: password
    tty: true
    stdin_open: true

  db:
    # build:
    #   context: .
    image: mysql:5.7
    # platform: linux/amd64
    platform: linux/x86_64
    ports:
      - '3306:3306'
      # - db_data:/var/lib/mysql
    volumes:
      - db_data:/var/lib/mysql
    extends:
      file: ./mysql/password.yml
      service: password

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80:80'
    volumes_from:
      - app

volumes:
  db_data: